# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" "snd-seq" "snd-rawmidi"];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.blacklistedKernelModules = ["mei_wdt"];
  # boot.extraModprobeConfig = ''options snd slots=snd-usb-audio,snd-hda-intel'';

  # hardware.trackpoint = {
  #                     enable = true;
  #                     sensitivity = 255;
  #                     speed = 255;
  # };
  #JACK ENABLE
  hardware.cpu.intel.updateMicrocode = true; 
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cc14be1d-bda9-4715-be6e-00ec19fe2657";
      fsType = "ext2";
    };

  nix.maxJobs = lib.mkDefault 4;
 # powerManagement.cpuFreqGovernor = "powersave";
}
