"""Base qutebrowser configuration that pulls colors from wallust output."""

from __future__ import annotations

from pathlib import Path
import dracula.draw

# Keep qutebrowser defaults unless overridden explicitly below.
config.load_autoconfig()

# Load the autogenerated palette produced by wallust (if present).
# colors_file = Path(__file__).with_name("colors.py")
# if colors_file.exists():
#     config.source(str(colors_file))
# else:
#     print(f"[qutebrowser] wallust colors not found at {colors_file}")


# Example personal preferences. Adjust as needed.
c.editor.command = ["emacsclient","-c", "{file}"]
c.auto_save.session = True
c.tabs.show = "multiple"
c.tabs.position = "top"

dracula.draw.blood(c, {
    'spacing': {
        'vertical': 6,
        'horizontal': 8
    }
})
