# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ modulesPath, config, lib, pkgs, ... }:

{
  imports =
    [ #<nixpkgs/nixos/modules/installer/scan/not-detected.nix>
      (modulesPath + "/installer/scan/not-detected.nix")

    ];

  swapDevices =
    [
      { device = "/var/swap-extra"; size=10240; }
    ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.extraModulePackages = [ ];
  hardware.cpu.amd.updateMicrocode = true;
  hardware.enableAllFirmware = true;
  services.fwupd.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/37afb3c1-54da-4cc2-9d40-280bc053ad12";
      fsType = "ext4";
    };       

  nix.maxJobs = "auto";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
